name: "Rust-Tests"

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests 
      working-directory: ./src-tauri
      run: yarn && cargo test
      
  todo_lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo_lib
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests 
      working-directory: ./todo_lib
      run: cargo test
      
  clippy_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy
    - run: yarn && cargo clippy
